# should be configured in ESP Home as a new device used
# used devices: NodeMCU + DHT20 humidity & temperature sensor
esphome:
  name: temperatursensor
  friendly_name: Temperatursensor
  includes:
    - custom_temp_sensor.h
  libraries:
    - Wire
    - "https://github.com/RobTillaart/DHT20"
esp8266:
  board: esp01_1m
logger:
api:
  encryption:
    key: "************"
ota:
  password: "************"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Custom SSID for ESP device"
    password: "************"
captive_portal:
sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new CustomTempSensorDH20();
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor,my_sensor->humidity_sensor};
  sensors:
  - name: "HomeTemp"
    unit_of_measurement: °C
    accuracy_decimals: 2
    icon: "mdi:temperature-celsius"
    device_class: "temperature"
    state_class: "measurement"
  - name: "HomeHumidity"
    accuracy_decimals: 2
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    device_class: "humidity"
    state_class: "measurement"
